### ISSUE TITLE
make the languageId of didOpen notifications configurable

### ISSUE THREAD

**Issue by ayame113** [atom-community/atom-languageclient#178]
According to the spec, the recommended markdown `languageId` for `textDocument/didOpen` requests is "markdown".
Currently, the markdown `languageId` is "github markdown", can you change it?

![image](https://user-images.githubusercontent.com/40050810/127034773-96b36b52-53d9-4aa5-bf1d-3daca0a52e7b.png)

(The [specifications](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocumentItem) say "If a document refers to one of the programming languages listed below it is recommended that clients use those ids.".)

**Comment by UziTech** [comment]
the languageId is set by the grammar name. If you want the languageid to be markdown you can use [language-markdown](https://atom.io/packages/language-markdown) instead of [language-gfm](https://atom.io/packages/language-gfm)

**Comment by UziTech** [comment]
I feel like we should leave this between the grammars and the servers. GFM should be processed differently than CommonMark (markdown). I think the servers might want to know which one they are receiving.

**Comment by ayame113** [comment]
> I think the servers might want to know which one they are receiving.

It makes sense.
How about allowing users of this package to configure languageId through the AutoLanguageClient?

example:
```ts
class FooBarLanguageClient extends AutoLanguageClient {
  getLanguageIdFromGrammarScope(scopeName: string): string|undefined {
    if (scopeName==='source.gfm') {
      return 'markdown'
    }
  }
}
```

**Comment by UziTech** [comment]
I think some sort of override would be ok. @ayame113 wanna create a PR?

**Comment by ayame113** [comment]
> wanna create a PR?

OK, I will do it.
