### ISSUE TITLE
Fix text completions

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-languageclient#18]
We should start with this: https://github.com/atom/atom-languageclient/pull/254

**Comment by UziTech** [comment]
When I looked into copying that PR to this repo it looks like most of the code has already been updated. I'm not sure how to rebase that PR onto the changes that have happened since it was opened.

**Comment by jonboiser** [comment]
A similar bug was reported downstream in the `ide-python` library.

https://github.com/atom-community/ide-python/issues/251

I was able to isolate it to the change here made in #100. When I revert the change on my local copy of `ide-python`'s dependencies, it fixes the issue. So there might be some interaction between the two issues.

**Comment by aminya** [comment]
> A similar bug was reported downstream in the `ide-python` library.
> 
> [atom-community/ide-python#251](https://github.com/atom-community/ide-python/issues/251)
> 
> I was able to isolate it to the change here made in #100. When I revert the change on my local copy of `ide-python`'s dependencies, it fixes the issue. So there might be some interaction between the two issues.

Thanks for the report. I transferred the issue.

**Comment by aminya** [comment]
Sometimes when I press `TAB` nothing gets written by autocomplete.

**Comment by UziTech** [comment]
> Sometimes when I press `TAB` nothing gets written by autocomplete. 

That seems like an issue for the autocomplete package.

**Comment by UziTech** [comment]
I'm pretty sure test completions are fixed in v1.0.6

If there are still issues create another issue with specific details.
